baseURL = 'https://cyrillesondag.github.io/'
languageCode = 'fr-fr'
title = 'Yet another tech blog'
theme = 'PaperMod'
copyright = 'Â© {year}'

# Enable emoji support
enableEmoji = true

# Enable Git info
enableGitInfo = true

# Google Analytics
# googleAnalytics = 'G-8KHJGZJ8WJ'

[params]
  # Site description
  description = "Blog technique sur le dÃ©veloppement, DevOps et Linux"
  author = "Cyrille Sondag"

  # Date format
  dateFormat = "2 January 2006"

  # Show reading time
  ShowReadingTime = true

  # Show share buttons
  ShowShareButtons = true

  # Show post navigation
  ShowPostNavLinks = true

  # Show breadcrumbs
  ShowBreadCrumbs = true

  # Show code copy button
  ShowCodeCopyButtons = true

  # Show table of contents
  ShowToc = true
  TocOpen = false

  # Show full content in RSS
  ShowFullTextinRSS = true

  # Comments (Disqus)
  comments = true
  disqusShortname = "github-blog-tpysk8cw2i"

  # Home page settings
  [params.homeInfoParams]
    Title = "Bienvenue ðŸ‘‹"
    Content = """
Blog technique abordant des sujets autour du dÃ©veloppement logiciel, DevOps, Linux et systemd.
"""

  # Social icons
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/CyrilleSondag"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/cyrillesondag"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:cyrille.sondag@gmail.com"

  # Profile mode (alternative to home info)
  [params.profileMode]
    enabled = false

  # Cover image settings
  [params.cover]
    linkFullImages = true
    responsiveImages = true

  # Edit post link
  [params.editPost]
    disabled = false

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Accueil"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    identifier = "search"
    name = "Rechercher"
    url = "/search/"
    weight = 40

# Markup configuration
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false
    style = "monokai"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Outputs
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Privacy settings
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

  [privacy.x]
    enableDNT = true

  [privacy.youtube]
    privacyEnhanced = true

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
